# Generated by Django 5.1.7 on 2025-03-19 19:20

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_bootcamp_type_təlimlər_bootcamp_tipi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='təlimlər',
            name='metinler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telimler_metinler', to='main.mətinlər'),
        ),
        migrations.AlterField(
            model_name='müəllimlər',
            name='image',
            field=models.ImageField(upload_to=main.models.upload_to_trainers),
        ),
        migrations.AlterField(
            model_name='mətinlər',
            name='certificate_image',
            field=models.ImageField(upload_to=main.models.upload_to_certificates),
        ),
        migrations.AlterField(
            model_name='mətinlər',
            name='image',
            field=models.ImageField(upload_to=main.models.upload_to_metinler),
        ),
        migrations.AlterField(
            model_name='mətinlər',
            name='trainings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metinler_trainings', to='main.təlimlər'),
        ),
        migrations.AlterField(
            model_name='məzunlar',
            name='image',
            field=models.ImageField(upload_to=main.models.upload_to_graduates),
        ),
        migrations.AlterField(
            model_name='təlimçilər',
            name='image',
            field=models.ImageField(upload_to=main.models.upload_to_trainers),
        ),
    ]
