# Generated by Django 5.1.7 on 2025-04-08 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_təlimlər_metinler_alter_müəllimlər_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='təlimçilər',
            name='metinler_temp',
            field=models.ManyToManyField(blank=True, related_name='trainers_temp', to='main.mətinlər'),
        ),
        migrations.AlterField(
            model_name='təlimçilər',
            name='metinler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trainers_old', to='main.mətinlər'),
        ),
    ]
