# Generated by Django 5.1.7 on 2025-04-10 08:37

import main.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20250408_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='təlimlər',
            name='metinler',
        ),
        migrations.RemoveField(
            model_name='təlimçilər',
            name='metinler_temp',
        ),
        migrations.AlterField(
            model_name='müəllimlər',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=main.models.upload_to_trainers),
        ),
        migrations.AlterField(
            model_name='mətinlər',
            name='certificate_image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=main.models.upload_to_certificates),
        ),
        migrations.AlterField(
            model_name='mətinlər',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=main.models.upload_to_metinler),
        ),
        migrations.AlterField(
            model_name='məzunlar',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=main.models.upload_to_graduates),
        ),
        migrations.AlterField(
        model_name='müəllimlər',
        name='image',
        field=models.ImageField(...),
    ),
        migrations.AlterField(
            model_name='təlimçilər',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=main.models.upload_to_trainers),
        ),
        migrations.RemoveField(
            model_name='təlimçilər',
            name='metinler',
        ),
        migrations.AddField(
            model_name='təlimçilər',
            name='metinler',
            field=models.ManyToManyField(related_name='trainers', to='main.mətinlər'),
        ),
    ]
