# Generated by Django 5.1.7 on 2025-04-10 08:51

import main.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_təlimlər_metinler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='müəllimlər',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=main.models.upload_to_trainers),
        ),
    ]
