# Generated by Django 5.1.7 on 2025-04-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_müəllimlər_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='təlimçilər',
            name='metinler',
        ),
        migrations.AddField(
            model_name='təlimçilər',
            name='telimler',
            field=models.ManyToManyField(related_name='trainers', to='main.təlimlər'),
        ),
    ]
