# Generated by Django 5.1.7 on 2025-04-24 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_emailsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessiyaQeydiyyati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('event_date', models.DateField(blank=True, help_text='Sessiyanın tarixi', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(help_text='Qeydiyyatın bağlı olduğu sessiya', on_delete=django.db.models.deletion.CASCADE, related_name='session_registrations', to='main.sessiyalar')),
                ('training', models.ForeignKey(help_text='Qeydiyyatın bağlı olduğu təlim', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='main.təlimlər')),
            ],
        ),
    ]
