# Generated by Django 5.1.7 on 2025-09-11 07:34

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_sessiyaqeydiyyati'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('image', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='certificates/images/')),
                ('image_en', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='certificates/images/')),
                ('file', models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='certificates/files/')),
                ('file_en', models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='certificates/files/')),
                ('date', models.CharField(max_length=100)),
                ('date_en', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
