# Generated by Django 5.1.7 on 2025-09-12 07:09

import main.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(storage=main.storage_backends.MediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file_en',
            field=models.FileField(storage=main.storage_backends.MediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(storage=main.storage_backends.MediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image_en',
            field=models.ImageField(storage=main.storage_backends.MediaStorage(), upload_to=''),
        ),
    ]
