# Generated by Django 5.1.7 on 2025-09-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_certificate_file_alter_certificate_file_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscription',
            name='program',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
