# Generated by Django 5.1.7 on 2025-09-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_emailsubscription_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsubscription',
            name='program',
        ),
    ]
