# Generated by Django 5.1.7 on 2025-09-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_emailsubscription_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscription',
            name='program',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
