# Generated by Django 5.1.7 on 2025-09-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_emailsubscription_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscription',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='email_subscription_pdfs/'),
        ),
    ]
