# Generated by Django 5.1.7 on 2025-09-23 09:20

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_programpdf_remove_emailsubscription_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programpdf',
            name='pdf',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='program_pdfs/'),
        ),
    ]
