"""
Django settings for dsa project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Database configuration
DATABASES = {
    'default': dj_database_url.config(default=os.getenv("DATABASE_URL"))
}

# Superuser credentials from environment variables
SUPERUSER_USERNAME = os.getenv('SUPERUSER_USERNAME', 'admin')  # Default: 'admin'
SUPERUSER_EMAIL = os.getenv('SUPERUSER_EMAIL', 'admin@example.com')  # Default: 'admin@example.com'
SUPERUSER_PASSWORD = os.getenv('SUPERUSER_PASSWORD', 'adminadmin')  # Default: 'adminpassword'

# Security settings
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# Production settings
DEBUG = False  # Changed to False for production security

ALLOWED_HOSTS = ['dsabackend-production-00f4.up.railway.app']  # Specific host for security

CSRF_TRUSTED_ORIGINS = [
    "https://dsabackend-production-00f4.up.railway.app"
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'corsheaders',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = False  # Set to False for security, use CORS_ALLOWED_ORIGINS instead if needed
# CORS_ALLOWED_ORIGINS = ['https://dsabackend-production-00f4.up.railway.app']  # Uncomment and configure if specific origins are needed

ROOT_URLCONF = 'dsa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Add template directories if needed
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dsa.wsgi.application'

# Database
DATABASES = {
    'default': dj_database_url.config(default=os.getenv("DATABASE_URL"))
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # For collectstatic

# Media files (for Railway volume)
MEDIA_URL = '/media/'
MEDIA_ROOT = '/app/media'  # Updated to match the mounted volume path

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
