name: Deploy to Railway

on:
  push:
    branches:
      - main # Trigger when there's a push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python and pip
        run: |
          sudo apt update
          sudo apt install python3 python3-pip -y

      - name: Create and Activate Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Install Dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Create Django Admin User
        env:
          DJANGO_SUPERUSER_USERNAME: dsa
          DJANGO_SUPERUSER_EMAIL: admin@dsa.az
          DJANGO_SUPERUSER_PASSWORD: admin123
        run: |
          source venv/bin/activate
          python manage.py createsuperuser --noinput || echo 'Admin user already exists'

      - name: Run Django Migrations
        run: |
          source venv/bin/activate
          python manage.py migrate

      - name: Deploy to Railway
        run: railway up --service=dsa_back_end
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
