name: Update Django Admin Superuser

on:
  push:
    branches:
      - main  # Trigger when there's a push to the main branch

jobs:
  update-admin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python and pip
        run: |
          sudo apt update
          sudo apt install python3 python3-pip -y

      - name: Create and Activate Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Install Dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Update Django Admin User
        env:
          DJANGO_SUPERUSER_USERNAME: admin
          DJANGO_SUPERUSER_EMAIL: newadmin@dsa.az  # Yeni e-posta
          DJANGO_SUPERUSER_PASSWORD: newpassword123  # Yeni şifre
        run: |
          source venv/bin/activate
          python manage.py shell -c "from django.contrib.auth.models import User; user = User.objects.get(username='admin'); user.email = '${DJANGO_SUPERUSER_EMAIL}'; user.set_password('${DJANGO_SUPERUSER_PASSWORD}'); user.save(); print('Admin user updated successfully.')"

      - name: Deploy to Railway
        run: railway up --service=dsa_back_end
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
